"""Initial migration

Revision ID: 7f893357f0d4
Revises: 
Create Date: 2026-02-02 16:29:58.598609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f893357f0d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_sid', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_token_token'), ['token'], unique=True)

    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_sid', sa.String(length=100), nullable=True),
    sa.Column('receiver_sid', sa.String(length=100), nullable=True),
    sa.Column('sender_name', sa.String(length=100), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    with op.batch_alter_table('admin_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_token_token'))

    op.drop_table('admin_token')
    # ### end Alembic commands ###
